"""Rechanging Victim db details

Revision ID: f7bbd84a5b26
Revises: 
Create Date: 2024-08-16 19:42:25.570081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7bbd84a5b26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('victim', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.BigInteger(), nullable=False))
        batch_op.create_unique_constraint('uq_long', ['longitude'])
        batch_op.create_unique_constraint('uq_lat', ['latitude'])
        batch_op.drop_column('phone_no')
        batch_op.drop_column('aadhar_pic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('victim', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aadhar_pic', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('phone_no', sa.BIGINT(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
